from enum import Enum

class BreakReasonTypes(str, Enum):
    BOREDOM = "boredom"
    BREATHLESSNESS = "breathlessness"
    DISTRACTION = "distraction"
    DRINK = "drink"
    EAT = "eat"
    EXHAUSTION = "exhaustion"
    HIGH_HEART_RATE = "high_heart_rate"
    INJURY = "injury"
    LOW_MOTIVATION = "low_motivation"
    MENTAL_FATIGUE = "mental_fatigue"
    MUSCLE_FATIGUE = "muscle_fatigue"
    NAVIGATION = "navigation"
    PAIN = "pain"
    REST = "rest"
    SOCIAL = "social"
    TECHNICAL_ISSUE = "technical_issue"
    TERRAIN = "terrain"
    TRAFFIC = "traffic"
    WAITING = "waiting"
    WEATHER_COLD = "weather_cold"
    WEATHER_HEAT = "weather_heat"
    WEATHER_RAIN = "weather_rain"
    WIND = "wind"