from enum import Enum

class HabitTypes(str, Enum):
    ALCOHOL = "alcohol"
    CAFFEINE = "caffeine"
    EXERCISE = "exercise"
    DRUGS = "drugs"
    EXPENDITURE = "expenditure"
    GAMING = "gaming"
    HEALTHY_EATING = "healthy_eating"
    HYDRATION = "hydration"
    HYGIENE = "hygiene"
    IMPULSE_CONTROL = "impulse_control"
    JOURNALING = "journaling"
    MINDFUL_BREAKS = "mindful_breaks"
    MOVEMENT = "movement"
    NUTRITION = "nutrition"
    READING = "reading"
    SCREEN_TIME = "screen_time"
    SKILL_PRACTICE = "skill_practice"
    SLEEPING = "sleeping"
    SLEEP_ROUTINE = "sleep_routine"
    SMOKE = "smoke"
    SOCIAL_CONTACTS = "social_contacting"
    SOCIAL_MEDIA = "social_media"
    SUGAR = "sugar"