from enum import Enum

class SideEffectTypes(str, Enum):
    ABDOMINAL_PAIN = "abdominal_pain"
    ANXIETY = "anxiety"
    CONFUSION = "confusion"
    DECREASED_APPETITE = "decreased_appetite"
    DECREASED_PULSE = "decreased_pulse"
    DIZZINESS = "dizziness"
    DRY_MOUTH = "dry_mouth"
    EUPHORIA = "euphoria"
    FATIGUE = "fatigue"
    HEADACHE = "headache"
    INCREASED_APPETITE = "increased_appetite"
    INCREASED_PULSE = "increased_pulse"
    INSOMNIA = "insomnia"
    LIMITED_COORDINATION = "limited_coordination"
    MEMORY_PROBLEMS = "memory_problems"
    MUSCLE_TENSION = "muscle_tension"
    NAUSEA = "nausea"
    NO = "no"
    PARANOIA = "paranoia"
    RED_EYES = "red_eyes"
    RESTLESSNESS = "restlessness"
    SHIVERING = "shivering"
    SWEATING = "sweating"
    VOMITING = "vomiting"