from enum import Enum

class TriggerTypes(str, Enum):
    ANXIETY = "anxiety"
    BOREDOM = "boredom"
    EMOTIONAL_SITUATION = "emotional_situation"
    FAMILY = "family"
    FATIGUE = "fatigue"
    FREETIME = "freetime"
    FRIENDS = "friends"
    GOING_TO_SLEEP = "going_to_sleep"
    HABIT = "habit"
    HAPPINESS = "happiness"
    HOBBY = "hobby"
    NATURE = "nature"
    PAUSE = "pause"
    SADNESS = "sadness"
    SCHOOL = "school"
    SOCIAL_SITUATION = "social_situation"
    STRESS = "stress"
    SUCCESS = "success"
    UNKNOWN = "unknown"
    WAKE_UP = "wake_up"
    WORK = "work"